#!/usr/bin/env python3

import json
import urllib.request

with urllib.request.urlopen("https://api.coinmarketcap.com/v1/ticker/raiblocks/?convert=BRL") as url:
    data = json.loads(url.read().decode())
    value = float(data[0]["price_brl"])
    print ("XRB: " + "R$" + str(float("{:.2f}".format(value))))

